[package]
name = "iceth"
version = "0.1.0"
description = "Ethereum on IC."
authors = ["John Plevyak <jplevyak@gmail.com>"]
readme = "README.md"
edition = "2021"

[dependencies]
candid = "0.9"
ic-canister-log = { git = "https://github.com/dfinity/ic", rev = "323bb2ceda477a6f7d13ab007c47935824b63150" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", rev = "323bb2ceda477a6f7d13ab007c47935824b63150" }
ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "323bb2ceda477a6f7d13ab007c47935824b63150" }
ic-certified-map = "0.3"
ic-cdk = "0.9"
ic-cdk-macros = "0.6"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"
json5 = "0.4"
num = "0.4"
num-traits = "0.2"
num-derive = "0.4"
serde = "1"
serde_bytes = "0.11"
serde_cbor = "0.11"
sha2 = "0.10"
url = "2.4"

[profile.release]
debug = false
lto = true
opt-level = 'z'
